### ISSUE TITLE
How to refresh data

### ISSUE THREAD

**Issue by jak1502** [gazoodle/geckolib#11]
Hi,

I have been playing around creating a home bridge plugin using you great library. I can't work out how to refresh the spa info though. I have tried the facade.spa.refresh() command but that doesn't appear to work.

**Comment by jak1502** [comment]
Was a problem my end. Refresh seems to work.

**Comment by stepir** [comment]
Hi @jak1502 - glad to hear you are working on it. Can't believe we both have the Yale alarm and and Gecko equipped hot tub :-D

I was really looking to implement something as well! main lack of the itouch app is the ability to control temperature with a scheduler imo.
