### ISSUE TITLE
More simple examples of getting status?

### ISSUE THREAD

**Issue by insaneoctane** [gazoodle/geckolib#18]
Excellent library! Just what I need, but I am a python newbie (learning just to access this library!). I could use a little more help on the syntax in python scripts that access spa status like pump1 or heater or ??. You gave an example of changing a pump, but what about just reading it?Maybe just suggest how one might generate the list of items that we have access to and what some syntax might look like to read those?  Very appreciative of what you have already done!

**Comment by gazoodle** [comment]
Thank you. I've been working on another of my projects recently but I've not forgotten the spa work. There are several issues currently open that I've been occasionally working on and hopefully I'll get back to them all soon. I'll give some thought to your question and update the docs.

**Comment by gazoodle** [comment]
Latest README has some examples
