### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-YJ5OrL/geckolib/

### ISSUE THREAD

**Issue by mawhot** [gazoodle/geckolib#19]
Hi 
When trying to install the library , I have this error 

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-YJ5OrL/geckolib/

Any idea ?

**Comment by brewston** [comment]
google/stackoverflow suggests downrev setup tools, so try :

`pip install -U setuptools`

**Comment by mawhot** [comment]
Hi , I have tried but still have the same issue . 
Line above show a syntax error 
  File "/tmp/pip-install-uA_8no/geckolib/src/geckolib/automation/__init__.py                                           ", line 3, in <module>
        from .base import GeckoAutomationBase
      File "/tmp/pip-install-uA_8no/geckolib/src/geckolib/automation/base.py", l                                           ine 29
        return f"{self._facade.unique_id}-{self._key}"
                                                     ^
    SyntaxError: invalid syntax

    ----------------------------------------

**Comment by gazoodle** [comment]
Do you have Python version >= 3.6. F-Strings are only supported in this version onward ...

**Comment by gazoodle** [comment]
Closing because issue is stale
