### ISSUE TITLE
Do you want anything returned from the new version?

### ISSUE THREAD

**Issue by mcfarlde** [gazoodle/geckolib#2]

**Comment by gazoodle** [comment]
If it’s working that’s good news. If you have a spa that isn’t an in.xm2 then doing some snapshots while exercising features that aren’t detected would be great. 

For example, you might have a waterfall or speaker lift or in.mix lighting system (which I don’t have).

v 0.3.7 will dump out the devices it has detected, which should be pumps, blowers and simple lights.

Start the client.py app, then 

1. `snapshot all devices off`
2. Turn on one your your unique devices (say waterfall)
3. `snapshot waterfall on`
4. Turn off the device
5. `snapshot waterfall off`
6. Repeat steps 2-6 for other devices
7. `exit`
8. Email `client.log` to gazoodle at hash dot fyi

Thank you!

PS the text after the `snapshot` command is just a descriptive marker so I can understand what the snapshot state represents.

**Comment by mcfarlde** [comment]
Mine is YE-5 like another on the original thread.  Nothing special.
