### ISSUE TITLE
Version not found

### ISSUE THREAD

**Issue by mmillmor** [gazoodle/geckolib#26]
I was having an issue with the code not finding the configuration for my spa (Cannot find XML configuration for inYT v65). I looked at the XML file at http://intouch.geckoal.com/gecko/prod/SpaPackStruct.xml and saw that for inYT the version number is v63. So I wondered what would happen if I just ignored the version, and I changed const.py to the following, to remove the version check

SPA_PACK_CONFIG_XPATH = "./ConfigStructures/ConfigStructure"
SPA_PACK_LOG_XPATH = "./LogStructures/LogStructure"

It appears to work fine when I do that. So the question is, should the code be ignoring the version, at least for some Plateforms?

**Comment by jimbodude** [comment]
I'm seeing the same behavior with v64.  `63` is the largest `LibRev` that I have in the XML coming back from the spa.

**Comment by mmillmor** [comment]
I have no reason to doubt anything you say, but do you know how Gecko get their app to work if not via the XML file at that URL? My spa can be controlled fine from the app, so do they have the XML file baked into the app at a later version, or are they using that same file and ignoring the version number? I appreciate that if they ignore it because they know they can, that is different from the open source code ignoring it on a hope that it is OK.

As for putting the file in the repo, the good thing is it is faster to install. The bad thing is that it is not up to date if they ever do make a change. Perhaps install instructions could say that people can check for a later version and overwrite if wanted? That covers all bases.

**Comment by gazoodle** [comment]
I don't think they do ignore the versions. There seem to be multiple places that the XML file is located. The previous URL as you noted, but also packed in to the Android APK distro, and also on another URL https://api-intouch2.geckoal.com/api/spapackstruct but we've not been able to successfully get it from there yet (BTH I've not given it much attention time)

The version available from http://intouch.geckoal.com/gecko/prod/SpaPackStruct.xml has a file version of 19, and does indeed only contain InYT layouts to lib version 63, but later versions have lib versions up to 81

For now, I'll add the data to the repo in some fashion and accept that it may get out-of-date but we can always update the repo when this occurs and go from there, probably better than what we have at present as it's quite a bit out of date at present.

**Comment by gazoodle** [comment]
As potentially misleading as the title on #12 is, this is a duplicate, so I’m closing this issue as most of the conversation is in the other thread.
