### ISSUE TITLE
Getting a Traceback Error

### ISSUE THREAD

**Issue by Zippochonda** [gazoodle/geckolib#28]
I installed this awesome libary on my openhabian system. It works but i get an error every minute:

LOG> ERROR Enum accessor inFloErrorType out-of-range for ['FLOW_OK', 'MODE_1_FAIL', 'MODE_1_AND_2_FAIL', 'MODE_1_AND_HEATING_FAIL', 'HEATING_FAIL']
Traceback (most recent call last):
  File "/home/openhabian/.local/lib/python3.7/site-packages/geckolib/driver/accessor.py", line 119, in _get_value
    data = self.items[data]
IndexError: list index out of range

**Comment by gazoodle** [comment]
I've just added some extra diags to help identify this a bit more but it's not a full PyPI release, so please grab the current code from GitHub. Specifically it's in the accessor.py file if you just want that.

**Comment by gazoodle** [comment]
This ought to be reported in a clean fashion now, please re-test
