### ISSUE TITLE
Optimise CPU usage - tweak ASYNCIO_SLEEP_TIMEOUT_FOR_YIELD

### ISSUE THREAD

**Issue by Ghawken** [gazoodle/geckolib#31]
Hi

Well done on this library - it works really well and obviously a lot of low-level capturing needed - Well Done!

I'm using it for a non-HA home automation plugin for Indigo (using python3).  All going pretty well, despite the async slight hurdles at my end..

I have noticed that CPU usage in my scenario sits around 15% for a mac Mini doing little else.  If I increase further your

const.py: Line: 18
ASYNCIO_SLEEP_TIMEOUT_FOR_YIELD to 0.1 I can drop CPU to less than 0.7% ?

May be a possible tweak for other systems?  As likely a sweat spot here somewhere.  Food for thought perhaps?

Thanks

Glenn

**Comment by xela1** [comment]
Well, I wish I looked here before spending a couple of hours tracing this  (starting at home assistant) to exactly the same place, and coming to exactly the same value too :), not sure the code is still being maintained though, I'll have to fork I guess

**Comment by gazoodle** [comment]
I’ve been sucked into another major project for the last 18 months and haven’t had the time to spend at all on the Gecko library of the HA integration, but that is coming to an end soon and I hope to be able to do some trivial maintenance late autumn (before the 2025.1 HA deadline for a couple of deprecation warnings), and then move on to some of the backlog.

**Comment by xela1** [comment]
I’ve actually just done a PR for the deprecated constants if you get time
to look at that. I think it’s fairly trivial. I’ve been testing it for a
couple of days and all seems good. I just found some time today to try and
trace the CPU issue

**Comment by gazoodle** [comment]
Hopefully this is fixed in the latest version
