### ISSUE TITLE
In.touch version 1

### ISSUE THREAD

**Issue by consolecwby** [gazoodle/geckolib#4]
Just curious if this code would work for the original in.touch I have tried looking at the packets during communication with the app and the module but i cannot understand it.

**Comment by gazoodle** [comment]
I don’t know, but if you download the repo, run the client.py from the tests folder and send the resulting client.log file to me, I’ll take a look. You can email it to gazoodle at hash dot fyi.

**Comment by gazoodle** [comment]
Did you get anywhere to see if this might help?

**Comment by marcoboutch** [comment]
you have in.touch2 upgrade program on gecko website for half price and you dont need return in.touch1. maybe you can resale your in.touch1....

**Comment by gazoodle** [comment]
Closing issue as it’s stale now and I have no way to move on without more info
