### ISSUE TITLE
PIP is WARNING that 'python-version>="3.7"' is now a non-standard dependency specifier.  It wiil be enforced soon!! 

### ISSUE THREAD

**Issue by maegibbons** [gazoodle/geckolib#44]
Hi

pip is objecting to your dependency specifier:

DEPRECATION: geckolib 0.4.8 has a non-standard dependency specifier python-version>="3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of geckolib or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Can you correct Please.

Krs

Mark

**Comment by gazoodle** [comment]
Should be fixed in v0.4.15
