### ISSUE TITLE
communication with Loxone smart home

### ISSUE THREAD

**Issue by damoxn** [gazoodle/geckolib#45]
hi guys,

sorry for my bad english, and please excuse me, I only have basic knowledge of programming.
Some python projects are already running on the raspberry.

I have upgradet my whirlpool with the in.touch.2 module and i want to usw it with my Loxone smart home control.
Probably not a complicated thing for professionals but I don't know how to switch between the "standard" and the "away" mode.
So when the Loxone energy manager says he has enough power from the photovoltaic - switch to "standard" heating, and when sun goes down switch to "away" oder eco mode.
Is there any option to control this script over UDP, HTTP or Mqtt?

thanks a lot

**Comment by Zippochonda** [comment]
Hey,
There is a geckoservice that opens a connection to mqtt.

https://github.com/kalinrow/geckoclient

damoxn ***@***.***> schrieb am So., 11. Feb. 2024, 11:28:

**Comment by gazoodle** [comment]
Closed, @Zippochonda answer seems to provide what's needed
