### ISSUE TITLE
Stop error with two spas in get_spa_from identifier

### ISSUE THREAD

**Issue by SchmidSP** [gazoodle/geckolib#9]
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    with GeckoLocator(CLIENT_ID1).get_spa_from_identifier('SPA80:1f:12:65:6b:1b') as locator1:
  File "C:\Users\Schmid\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\geckolib\locator.py", line 90, in get_spa_from_identifier
    return next(spa for spa in self.spas if spa.identifier == identifier)
StopIteration

Any Idea?

**Comment by gazoodle** [comment]
I'm not sure the syntax you're using is going to do what you want. The `locator` class doesn't seem to have found any spas by the time you call `get_spa_from_identifier`. Going forward, I'll make sure to add more diagnostics to help identify why this doesn't work, but for now, this ought to help...
```python

# Find the spas on the network
with GeckoLocator(CLIENT_UUID) as locator:
    # Connect with a specific spa
    with locator.get_spa_from_identifier(SPA_ID).get_facade() as facade:
        # Show some info
        print(facade.water_heater)
```

**Comment by SchmidSP** [comment]
Hi,

I got the error!
I have missunderstand the locater parameter.
Now it works:

import time
from geckolib import GeckoLocator   # pylint: disable=import-error,wrong-import-position

# Replace with your own UUID, see https://www.uuidgenerator.net/>
CLIENT_ID = "xxx"

with GeckoLocator(CLIENT_ID) as locator:

    with locator.get_spa_from_identifier("SPA80:1f:12:65:6b:1b").get_facade() as facade:
        # Show some info
        print(facade.name)
        print(facade.water_heater)
        print(facade.water_care)
        print(facade.pumps)
        print(facade.blowers)
        print(facade.lights)
        print(facade.reminders)

    with locator.get_spa_from_identifier("SPA80:1f:12:65:c8:41").get_facade() as facade:
        # Show some info
        print(facade.name)
        print(facade.water_heater)
        print(facade.water_care)
        print(facade.pumps)
        print(facade.blowers)
        print(facade.lights)
        print(facade.reminders)

Thanks! Good Job.

Do you plan a homebridge or openhab plugin?

Greetings
Klaus

________________________________
Von: gazoodle <notifications@github.com>
Gesendet: Montag, 30. November 2020 08:00
An: gazoodle/geckolib <geckolib@noreply.github.com>
Cc: Klaus Schmid <info@klausschmid.de>; Author <author@noreply.github.com>
Betreff: Re: [gazoodle/geckolib] Stop error with two spas in get_spa_from identifier (#9)


I'm not sure the syntax you're using is going to do what you want. The locator class doesn't seem to have found any spas by the time you call get_spa_from_identifier. Going forward, I'll make sure to add more diagnostics to help identify why this doesn't work, but for now, this ought to help...

# Find the spas on the network
with GeckoLocator(CLIENT_UUID) as locator:
    # Connect with a specific spa
    with locator.get_spa_from_identifier(SPA_ID).get_facade() as facade:
        # Show some info
        print(facade.water_heater)

**Comment by gazoodle** [comment]
Great, I’ll close this issue then!
